language: node_js
env:
  global:
  - SAUCE_USERNAME: chunpu2
  - secure: PDjYv4YHrNaz/Yo0pgDQbCag8mvl9UOZB2SsAIPe26kPYRuLHIjpDTEUhO1XQO3ibU2fzzWfioglXX8XqJ83irEOA0T7SYJnstB+cSYgTZ1Jt2Xt41HY07LWRQWksAfPhCDKPfIcw3Z7xCwCl+iJsDGrXclnUQVGLXYMXj60u/Q=
